name: Build and Deploy Docs

  #on:
  #  push:
  #    branches:
      #      - main  # or 'master', depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          pip install sphinx nbsphinx sphinx_rtd_theme ipython ipykernel
          python -m ipykernel install --user --name python3
          pip install .

      - name: Build Sphinx Docs
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
